name: CI

on:
  push:
  pull_request:

jobs:
  py-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Byte-compile Python scripts
        run: |
          python -m compileall -q -x 'iprscan5_urllib3' scripts
